<a href="https://colab.research.google.com/github/ilansarbac95/DI158/blob/main/intronumpy_exercises_xp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Exercice 1 : Créer un array de 0 à 9
arr1 = np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exercice 2 : Convertir une liste float en array d'entiers
liste = [3.14, 2.17, 6., 1., 2.]
arr2 = np.array(liste, dtype=int)
print(arr2)


[3 2 6 1 2]


In [ ]:
# Exercice 3 : Créer une matrice 3x3 avec les nombres de 1 à 9
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Exercice 4 : Créer une matrice 4x5 avec des valeurs aléatoires entre 0 et 1
arr4 = np.random.rand(4, 5)
print(arr4)


[[0.16867516 0.72857351 0.2288575  0.99321    0.52354971]
 [0.36756437 0.72021425 0.88624935 0.87120057 0.41772587]
 [0.88627357 0.76375638 0.02635177 0.3127932  0.0354776 ]
 [0.94142849 0.66726869 0.35477715 0.80829002 0.42072808]]


In [ ]:
# Exercice 5 : Créer une matrice et sélectionner la 2e ligne
arr5 = np.array([[21, 22, 23, 22, 23], [20, 21, 22, 23, 24], [21, 22, 23, 22, 21]])
second_row = arr5[1]
print(second_row)


[20 21 22 23 24]


In [ ]:
# Exercice 6 : Inverser un array
arr6 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
reversed_arr = arr6[::-1]
print(reversed_arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exercice 7 : Créer une matrice identité 4x4
identity = np.eye(4)
print(identity)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Exercice 8 : Calculer somme et moyenne d’un array
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
total = np.sum(arr8)
average = np.mean(arr8)
print("Sum:", total, "Average:", average)


Sum: 45 Average: 5.0


In [ ]:
# Exercice 9 : Créer un array de 1 à 20, reshape en 4x5
arr9 = np.arange(1, 21).reshape(4, 5)
print(arr9)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# Exercice 10 : Extraire les nombres impairs
arr10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr10[arr10 % 2 == 1]
print(odd_numbers)


[1 3 5 7 9]
